Friendly error messages
=======================

AvantPy aims to provide friendlier feedback when an exception
is raised than what is done by Python.
Such feedback will also be available in languages other than English.

.. note::

     The content of this page is generated by running
     tb_pyupper.py located in the ``tests/pyupper/`` directory.
     This needs to be done explicitly, independently of updating the
     documentation using Sphinx.

AvantPy version: 0.0.7
Python version: 3.7.0



IfNobreakError
-------------- 

Example::


    AVANTPY EXCEPTION: IfNobreakError

    Error found in file raise_if_nobreak.pyupper on line 4.

    Dialect used: pyupper

       2: if True:
       3:     pass
    -->4: NOBREAK:

    The AvantPy NOBREAK keyword cannot be used in
    an IF/ELIF/ELSE clause (Python: if/elif/else).


MismatchedBracketsError
----------------------- 

Example::


    AVANTPY EXCEPTION: MismatchedBracketsError

    Error found in file raise_mismatched_brackets.pyupper on lines [2 - 10].

    Dialect used: pyupper

    -->2: a = (1,   # Large number of lines between ( and ]
       3:     2,
       4:     3, 4,
           ...
        8:     8,
        9:     9,
    -->10: ]

    The opening ( does not match the closing ].


MissingLeftBracketError
----------------------- 

Example::


    AVANTPY EXCEPTION: MissingLeftBracketError

    Error found in file raise_missing_left_bracket.pyupper on line 5.

    Dialect used: pyupper

       4:     3, 4,)
    -->5:     )
       6: b = 3

    The closing ) does not match anything.


MissingRepeatError
------------------ 

Example::


    AVANTPY EXCEPTION: MissingRepeatError

    Error found in file raise_missing_repeat.pyupper on line 3.

    Dialect used: pyupper

       2: x = 0
    -->3: UNTIL x == 2:
       4:     x += 1

    The AvantPy UNTIL keyword can be used only when preceded by
    REPEAT.


Example 2::

    AVANTPY EXCEPTION: MissingRepeatError

    Error found in file raise_missing_repeat2.pyupper on line 3.

    Dialect used: pyupper

       2: x = 0
    -->3: FOREVER:
       4:     x += 1

    The AvantPy FOREVER keyword can be used only when preceded by
    REPEAT.


NobreakFirstError
----------------- 

Example::


    AVANTPY EXCEPTION: NobreakFirstError

    Error found in file raise_nobreak_first.pyupper on line 3.

    Dialect used: pyupper

       2: # Need to prevent NOBREAK being replaced by 'else' in this situation.
    -->3: a = 1 if True NOBREAK 3
       4: 

    The AvantPy NOBREAK keyword can be used instead of ELSE (Python: else)
    only when it begins a new statement for loops.


NobreakSyntaxError
------------------ 

Example::


    AVANTPY EXCEPTION: NobreakSyntaxError

    Error found in file raise_nobreak_syntax.pyupper on line 4.

    Dialect used: pyupper

       3: a = 1
    -->4: NOBREAK: pass
       5: 

    The AvantPy NOBREAK keyword can only be used as a replacement
    of ELSE (Python: else) with a matching FOR or WHILE loop
    (Python: for/while).


RepeatFirstError
---------------- 

Example::


    AVANTPY EXCEPTION: RepeatFirstError

    Error found in file raise_repeat_first.pyupper on line 3.

    Dialect used: pyupper

       2: # Catch an early case of using REPEAT not to begin a loop
    -->3: a = REPEAT
       4: 

    The AvantPy REPEAT keyword can only be used to begin
    a new loop (Python: equivalent to 'for' or 'while' loop).


TryNobreakError
--------------- 

Example::


    AVANTPY EXCEPTION: TryNobreakError

    Error found in file raise_try_nobreak.pyupper on line 7.

    Dialect used: pyupper

       3:     TRY:
       4:         A = 1
       5:     EXCEPT:
       6:         A = 2
    -->7:     NOBREAK:

    The AvantPy NOBREAK keyword cannot be used in
    a TRY/EXCEPT/ELSE/FINALLY clause (Python: try/except/else/finally).


UnknownLanguageError
-------------------- 

Example::


    AVANTPY EXCEPTION: UnknownLanguageError


    The following unknown language was requested: xx.
    The known languages are: ['en', 'fr', 'upper'].


UnknownDialectError
------------------- 

Example::


    AVANTPY EXCEPTION: UnknownDialectError


    The following unknown dialect was requested: pyxx.
    The known dialects are: ['pyen', 'pyes', 'pyfr', 'pyupper'].


UnexpectedError
--------------- 

Example::

    No example found yet.

