# English translation for AvantPy
# André Roberge <andre.roberge@gmail.com>.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2019-04-03 22:18-0300\n"
"PO-Revision-Date: 2019-04-03 22:29-0300\n"
"Last-Translator: André Roberge <andre.roberge@gmail.com>\n"
"Language-Team: \n"
"Language: en\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 2.2.1\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: console.py:95
msgid "UNHANDLED EXCEPTION in console.py. This should not happen."
msgstr ""

#: exception_handling.py:79
msgid ""
"An exception was raised for which we have no simplified traceback:\n"
msgstr ""
"An exception was raised for which we have no simplified traceback:\n"

#: exception_handling.py:120
msgid ""
"\n"
"    AVANTPY EXCEPTION: IfNobreakError\n"
"\n"
"    Error found in file '{filename}' on line {nobreak_linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{nobreak_kwd}' keyword cannot be used in\n"
"    an '{if_kwd}/{elif_kwd}/{else_kwd}' clause (Python: if/elif/"
"else).\n"
"\n"
msgstr ""
"\n"
"    AvantPy exception: IfNobreakError\n"
"\n"
"    Error found in file '{filename}' on line {nobreak_linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{nobreak_kwd}' keyword cannot be used in\n"
"    an '{if_kwd}/{elif_kwd}/{else_kwd}' clause (Python: if/elif/"
"else).\n"
"\n"

#: exception_handling.py:158
msgid ""
"\n"
"    AVANTPY EXCEPTION: MismatchedBracketsError\n"
"\n"
"    Error found in file '{filename}' on lines [{begin} - {end}].\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The opening {open_bracket} does not match the closing "
"{close_bracket}.\n"
"\n"
msgstr ""
"\n"
"    AvantPy exception: MismatchedBracketsError\n"
"\n"
"    Error found in file '{filename}' on lines [{begin} - {end}].\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The opening {open_bracket} does not match the closing "
"{close_bracket}.\n"
"\n"

#: exception_handling.py:195
msgid ""
"\n"
"    AVANTPY EXCEPTION: MissingLeftBracketError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The closing {bracket} does not match anything.\n"
"\n"
msgstr ""
"\n"
"    AvantPy exception: MissingLeftBracketError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The closing {bracket} does not match anything.\n"
"\n"

#: exception_handling.py:230
msgid ""
"\n"
"    AVANTPY EXCEPTION: MissingRepeatColonError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    A statement beginning with the '{repeat_kwd}' keyword must be on a "
"single\n"
"    line ending with a colon (:) that indicates the beginning of an "
"indented\n"
"    block of code, with no other colon appearing on that line.\n"
"\n"
msgstr ""
"\n"
"    AvantPy exception: MissingRepeatColonError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    A statement beginning with the '{repeat_kwd}' keyword must be on a "
"single\n"
"    line ending with a colon (:) that indicates the beginning of an "
"indented\n"
"    block of code, with no other colon appearing on that line.\n"
"\n"

#: exception_handling.py:267
msgid ""
"\n"
"    AVANTPY EXCEPTION: MissingRepeatError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{keyword}'' keyword can be used only when preceded by "
"'{repeat_kwd}'.\n"
"\n"
msgstr ""
"\n"
"    AvantPy exception: MissingRepeatError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{keyword}' keyword can be used only when preceded by "
"'{repeat_kwd}'.\n"
"\n"

#: exception_handling.py:314
msgid ""
"\n"
"    PYTHON EXCEPTION: {python_display}\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    A NameError exception indicates that a variable or\n"
"    function name is not known to Python.\n"
"    Most often, this is because there is a spelling mistake; however,\n"
"    sometimes it is because it is used before being defined or given a "
"value.\n"
"    In your program, the unknown name is '{var_name}'.\n"
"\n"
msgstr ""
"\n"
"    Python exception: {python_display}\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    A NameError exception indicates that a variable or\n"
"    function name is not known to Python.\n"
"    Most often, this is because there is a spelling mistake; however,\n"
"    sometimes it is because it is used before being defined or given a "
"value.\n"
"    In your program, the unknown name is '{var_name}'.\n"
"\n"

#: exception_handling.py:355
msgid ""
"\n"
"    AVANTPY EXCEPTION: NobreakFirstError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{nobreak_kwd}' keyword can be used instead of "
"'{else_kwd}'\n"
"    (Python: else) only when it begins a new statement in\n"
"    '{for_kwd}/{while_kwd}' loops (Python: for/while).\n"
"\n"
msgstr ""
"\n"
"    AvantPy exception: NobreakFirstError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{nobreak_kwd}' keyword can be used instead of else\n"
"    only when it begins a new statement in '{for_kwd}/{while_kwd}' "
"loops (Python: for/while).\n"
"\n"

#: exception_handling.py:395
msgid ""
"\n"
"    AVANTPY EXCEPTION: NobreakSyntaxError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{nobreak_kwd}' keyword can only be used as a "
"replacement\n"
"    of '{else_kwd}' (Python: else) with a matching '{for_kwd}' or\n"
"    '{while_kwd}' loop (Python: for/while).\n"
"\n"
msgstr ""
"\n"
"    AvantPy exception: NobreakSyntaxError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{nobreak_kwd}' keyword can only be used as a "
"replacement\n"
"    of '{else_kwd}' (Python: else) with a matching '{for_kwd}' or\n"
"    '{while_kwd}' loop (Python: for/while).\n"
"\n"

#: exception_handling.py:435
msgid ""
"\n"
"    AVANTPY EXCEPTION: RepeatFirstError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{repeat_kwd}' keyword can only be used to begin\n"
"    a new loop (Python: equivalent to 'for' or 'while' loop).\n"
"\n"
msgstr ""
"\n"
"    AvantPy exception: RepeatFirstError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{repeat_kwd}' keyword can only be used to begin\n"
"    a new loop (Python: equivalent to 'for' or 'while' loop).\n"
"\n"

#: exception_handling.py:470
msgid ""
"\n"
"    AVANTPY EXCEPTION: TryNobreakError\n"
"\n"
"    Error found in file '{filename}' on line {nobreak_linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{nobreak_kwd}' keyword cannot be used in\n"
"    a '{try_kwd}/{except_kwd}/{else_kwd}/{finally_kwd}' clause\n"
"    (Python: try/except/else/finally).\n"
"\n"
msgstr ""
"\n"
"    AvantPy exception: TryNobreakError\n"
"\n"
"    Error found in file '{filename}' on line {nobreak_linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{nobreak_kwd}' keyword cannot be used in\n"
"    a '{try_kwd}/{except_kwd}/{else_kwd}/{finally_kwd}' clause\n"
"    (Python: try/except/else/finally).\n"
"\n"

#: exception_handling.py:505
msgid ""
"\n"
"    AVANTPY EXCEPTION: UnknownDialectError\n"
"\n"
"    The following unknown dialect was requested: {dialect}.\n"
"\n"
"    The known dialects are: {all_dialects}.\n"
"\n"
msgstr ""
"\n"
"    AvantPy exception: UnknownDialectError\n"
"\n"
"    The following unknown dialect was requested: {dialect}.\n"
"\n"
"    The known dialects are: {all_dialects}.\n"
"\n"

#: exception_handling.py:523
msgid ""
"\n"
"    AVANTPY EXCEPTION: UnknownLanguageError\n"
"\n"
"    The following unknown language was requested: {lang}.\n"
"\n"
"    The known languages are: {all_langs}.\n"
"\n"
msgstr ""
"\n"
"    AvantPy exception: UnknownLanguageError\n"
"\n"
"    The following unknown language was requested: {lang}.\n"
"\n"
"    The known languages are: {all_langs}.\n"
"\n"

#: import_hook.py:36
msgid "Cannot find main module: "
msgstr ""

#: session.py:168
msgid "    ==> LANGUAGE: {lang} | AVANTPY DIALECT: {dialect}"
msgstr "    ==> Language: {lang} | AvantPy dialect: {dialect}"
