# French translation for AvantPy
# André Roberge <andre.roberge@gmail.com>.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2019-04-03 07:12-0300\n"
"PO-Revision-Date: 2019-04-03 07:19-0300\n"
"Last-Translator: André Roberge <andre.roberge@gmail.com>\n"
"Language-Team: \n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 2.2.1\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: console.py:95
msgid "UNHANDLED EXCEPTION in console.py. This should not happen."
msgstr "Exception imprévue dans console.py. Ceci ne devrait pas arriver."

#: exception_handling.py:79
msgid "An exception was raised for which we have no simplified traceback:\n"
msgstr ""
"Une exception pour laquelle nous n'avons pas de traceback simplifiée a été "
"soulevée :\n"

#: exception_handling.py:130
msgid ""
"\n"
"    AVANTPY EXCEPTION: IfNobreakError\n"
"\n"
"    Error found in file '{filename}' on line {nobreak_linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy {nobreak_kwd} keyword cannot be used in\n"
"    an IF/ELIF/ELSE clause (Python: if/elif/else).\n"
"\n"
msgstr ""
"\n"
"    Exception AvantPy : IfNobreakError\n"
"\n"
"    Erreur trouvée dans le fichier '{filename}' à la ligne "
"{nobreak_linenumber}.\n"
"\n"
"    Dialecte utilisé : {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    Le mot-clé {nobreak_kwd} spécifique à Avantpy ne peut pas être utilisé\n"
"    dans un énoncé si/sinonsi/sinon (Python: if/elif/else).\n"
"\n"

#: exception_handling.py:167
msgid ""
"\n"
"    AVANTPY EXCEPTION: MismatchedBracketsError\n"
"\n"
"    Error found in file '{filename}' on lines [{begin} - {end}].\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The opening {open_bracket} does not match the closing {close_bracket}.\n"
"\n"
msgstr ""
"\n"
"    Exception AvantPy : MismatchedBracketsError\n"
"\n"
"    Erreur trouvée dans le fichier '{filename}' aux lignes [{begin} - "
"{end}].\n"
"\n"
"    Dialecte utilisé : {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    Le symbole gauche {open_bracket} ne correspond pas au symbole droit "
"{close_bracket}.\n"
"\n"

#: exception_handling.py:202
msgid ""
"\n"
"    AVANTPY EXCEPTION: MissingLeftBracketError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The closing {bracket} does not match anything.\n"
"\n"
msgstr ""
"\n"
"    Exception AvantPy : MissingLeftBracketError\n"
"\n"
"    Erreur trouvée dans le fichier '{filename}' à la ligne {linenumber}.\n"
"\n"
"    Dialecte utilisé : {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    Le symbole droit {bracket} n'a pas de symbole gauche correspondant.\n"
"\n"

#: exception_handling.py:237
msgid ""
"\n"
"    AVANTPY EXCEPTION: MissingRepeatColonError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    A statement beginning with the '{repeat_kwd}' keyword must be on a "
"single\n"
"    line ending with a colon (:) that indicates the beginning of an "
"indented\n"
"    block of code, with no other colon appearing on that line.\n"
"\n"
msgstr ""
"\n"
"    Exception AvantPy : RepeatFirstError\n"
"\n"
"    Erreur trouvée dans le fichier '{filename}' à la ligne {linenumber}.\n"
"\n"
"    Dialecte utilisé : {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    Un énoncé débutant avec le mot clé '{repeat_kwd}' spécifique à Avantpy\n"
"    doit être sur une seule ligne terminant avec deux points (:) qui "
"indiquent\n"
"    le début d'un bloc de code de code indenté, sans qu'il n'y ait\n"
"    d'autre deux points qui apparaissent sur cette ligne.\n"
"\n"

#: exception_handling.py:275
msgid ""
"\n"
"    AVANTPY EXCEPTION: MissingRepeatError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{keyword}'' keyword can be used only when preceded by "
"'{repeat_kwd}'.\n"
"\n"
msgstr ""
"\n"
"    Exception AvantPy : MissingRepeatError\n"
"\n"
"    Erreur trouvée dans le fichier '{filename}' à la ligne {linenumber}.\n"
"\n"
"    Dialecte utilisé: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    Le mot-clé '{keyword}' spécifique à Avantpy peut seulement être "
"utilisé\n"
"    s'il est précédé de '{repeat_kwd}'.\n"
"\n"

#: exception_handling.py:321
msgid ""
"\n"
"    PYTHON EXCEPTION: {python_display}\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    A NameError exception indicates that a variable or\n"
"    function name is not known to Python.\n"
"    Most often, this is because there is a spelling mistake; however,\n"
"    sometimes it is because it is used before being defined or given a "
"value.\n"
"    In your program, the unknown name is '{var_name}'.\n"
"\n"
msgstr ""
"\n"
"    Exception Python : {python_display}\n"
"\n"
"    Erreur trouvée dans le fichier '{filename}' à la ligne {linenumber}.\n"
"\n"
"    Dialecte utilisé : {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    Une exception de type NameError indique que le nom d'une variable\n"
"    ou d'une fonction utilisée dans votre programme est inconnu par "
"Python.\n"
"    Le plus souvent, ceci se produit parce que vous faites une faute\n"
"    d'orthographe dans l'écriture de votre variable ou de votre fonction;\n"
"    ceci peut également se produire si vous invoquez cette fonction ou "
"utilisez\n"
"    cette variable sans l'avoir définie auparavant.\n"
"    Dans votre programme, le nom inconnu est '{var_name}'.\n"
"\n"

#: exception_handling.py:361
msgid ""
"\n"
"    AVANTPY EXCEPTION: NobreakFirstError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{nobreak_kwd}' keyword can be used instead of ELSE\n"
"    (Python: else) only when it begins a new statement in FOR/WHILE loops.\n"
"\n"
msgstr ""
"\n"
"    Exception AvantPy : NobreakFirstError\n"
"\n"
"    Erreur trouvée dans le fichier '{filename}' à la ligne {linenumber}.\n"
"\n"
"    Dialecte utilisé : {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    Le mot-clé '{nobreak_kwd}' spécifique à Avantpy peut seulement être "
"utilisé\n"
"    au lieu de sinon (Python: else) lorsqu'il débute un nouvel énoncé\n"
"    dans des boucles 'pour' ou 'tantque' (Python: for/while).\n"
"\n"

#: exception_handling.py:398
msgid ""
"\n"
"    AVANTPY EXCEPTION: NobreakSyntaxError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{nobreak_kwd}' keyword can only be used as a replacement\n"
"    of ELSE (Python: else) with a matching FOR or WHILE loop\n"
"    (Python: for/while).\n"
"\n"
msgstr ""
"\n"
"    Exception AvantPy : IfNobreakError\n"
"\n"
"    Erreur trouvée dans le fichier '{filename}' à la ligne {linenumber}.\n"
"\n"
"    Dialecte utilisé : {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    Le mot-clé '{nobreak_kwd}' spécifique à Avantpy peut seulement être "
"utilisé\n"
"    au lieu de sinon (Python: else) lorsqu'il débute un nouvel énoncé\n"
"    dans des boucles 'pour' ou 'tantque' (Python: for/while).\n"
"\n"

#: exception_handling.py:435
msgid ""
"\n"
"    AVANTPY EXCEPTION: RepeatFirstError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{repeat_kwd}' keyword can only be used to begin\n"
"    a new loop (Python: equivalent to 'for' or 'while' loop).\n"
"\n"
msgstr ""
"\n"
"    Exception AvantPy : RepeatFirstError\n"
"\n"
"    Erreur trouvée dans le fichier '{filename}' à la ligne {linenumber}.\n"
"\n"
"    Dialecte utilisé : {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    Le mot-clé '{repeat_kwd}' spécifique à Avantpy peut seulement être "
"utilisé\n"
"    pour débuter une nouvelle boucle 'pour' ou 'tantque'\n"
"    (équivalent Python: 'for' ou 'while').\n"
"\n"

#: exception_handling.py:471
msgid ""
"\n"
"    AVANTPY EXCEPTION: TryNobreakError\n"
"\n"
"    Error found in file '{filename}' on line {nobreak_linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy '{nobreak_kwd}' keyword cannot be used in\n"
"    a TRY/EXCEPT/ELSE/FINALLY clause (Python: try/except/else/finally).\n"
"\n"
msgstr ""
"\n"
"    Exception AvantPy : TryNobreakError\n"
"\n"
"    Erreur trouvée dans le fichier '{filename}' à la ligne "
"{nobreak_linenumber}.\n"
"\n"
"    Dialecte utilisé : {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    Le mot-clé '{nobreak_kwd}' spécifique à Avantpy ne peut pas être "
"utilisé dans\n"
"    un énoncé essayer/siexception/sinon/finalement (Python: try/except/else/"
"finally).\n"
"\n"

#: exception_handling.py:495
msgid ""
"\n"
"    AVANTPY EXCEPTION: UnknownDialectError\n"
"\n"
"    The following unknown dialect was requested: {dialect}.\n"
"\n"
"    The known dialects are: {all_dialects}.\n"
"\n"
msgstr ""
"\n"
"    Exception AvantPy : UnknownDialectError\n"
"\n"
"    Le dialecte inconnu suivant a été demandé : {dialect}.\n"
"\n"
"    Les dialectes connus sont : {all_dialects}.\n"
"\n"

#: exception_handling.py:515
msgid ""
"\n"
"    AVANTPY EXCEPTION: UnknownLanguageError\n"
"\n"
"    The following unknown language was requested: {lang}.\n"
"\n"
"    The known languages are: {all_langs}.\n"
"\n"
msgstr ""
"\n"
"    Exception AvantPy : UnknownLanguageError\n"
"\n"
"    Le langage inconnu suivant a été demandé : {lang}.\n"
"\n"
"    Les langages connus sont : {all_langs}.\n"
"\n"

#: import_hook.py:36
msgid "Cannot find main module: "
msgstr "Le module principal ('main') ne peut pas être trouvé : "

#: session.py:168
msgid "    ==> LANGUAGE: {lang} | AVANTPY DIALECT: {dialect}"
msgstr "    ==> Langue : {lang} | dialecte AvantPy : {dialect}"
